<#
    Palworld Relic Teleporter
    Windows Forms popup

    This script displays the relic list generated by main.lua. It does not
    modify Palworld directly. When the user selects a relic, the script writes
    its numeric index to a command file. The UE4SS Lua script reads that index
    and performs the teleportation on the Unreal Engine game thread.
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$DataFile,

    [Parameter(Mandatory = $true)]
    [string]$CommandFile,

    [Parameter(Mandatory = $true)]
    [string]$LockFile,

    [Parameter(Mandatory = $true)]
    [string]$UiCommandFile
)

# Windows Forms provides a lightweight native popup without requiring extra
# third-party dependencies.
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

# Small Win32 helper used to restore focus to Palworld after a teleport request.
Add-Type @"
using System;
using System.Runtime.InteropServices;

public static class NativeWindowTools
{
    [DllImport("user32.dll")]
    public static extern bool SetForegroundWindow(IntPtr hWnd);

    [DllImport("user32.dll")]
    public static extern bool ShowWindowAsync(IntPtr hWnd, int nCmdShow);
}
"@

[System.Windows.Forms.Application]::EnableVisualStyles()

# ---------------------------------------------------------------------------
# Single-instance handling
# ---------------------------------------------------------------------------

function Test-ExistingMenu {
    if (-not (Test-Path -LiteralPath $LockFile)) {
        return $false
    }

    try {
        $existingPidText = [System.IO.File]::ReadAllText($LockFile).Trim()
        $existingPid = 0

        if ([int]::TryParse($existingPidText, [ref]$existingPid)) {
            $existingProcess = Get-Process -Id $existingPid -ErrorAction SilentlyContinue

            if ($null -ne $existingProcess) {
                # Ask the already running popup to reload its data and return
                # to the foreground, then terminate this duplicate process.
                [System.IO.File]::WriteAllText($UiCommandFile, "SHOW")
                return $true
            }
        }
    }
    catch {
        # A malformed or inaccessible lock file is treated as stale.
    }

    Remove-Item -LiteralPath $LockFile -Force -ErrorAction SilentlyContinue
    return $false
}

if (Test-ExistingMenu) {
    exit
}

[System.IO.File]::WriteAllText($LockFile, [string]$PID)

# ---------------------------------------------------------------------------
# Main window
# ---------------------------------------------------------------------------

$form = New-Object System.Windows.Forms.Form
$form.Text = "Palworld - Relic Teleporter"
$form.StartPosition = "CenterScreen"
$form.Size = New-Object System.Drawing.Size(1080, 700)
$form.MinimumSize = New-Object System.Drawing.Size(760, 450)
$form.TopMost = $true
$form.KeyPreview = $true
$form.BackColor = [System.Drawing.Color]::FromArgb(28, 30, 36)

$title = New-Object System.Windows.Forms.Label
$title.Text = "Statues and Relics"
$title.AutoSize = $true
$title.Font = New-Object System.Drawing.Font(
    "Segoe UI",
    17,
    [System.Drawing.FontStyle]::Bold
)
$title.ForeColor = [System.Drawing.Color]::White
$title.Location = New-Object System.Drawing.Point(18, 14)
$form.Controls.Add($title)

$subtitle = New-Object System.Windows.Forms.Label
$subtitle.Text = "Double-click a row, press Enter, or select it and click Teleport."
$subtitle.AutoSize = $true
$subtitle.Font = New-Object System.Drawing.Font("Segoe UI", 9)
$subtitle.ForeColor = [System.Drawing.Color]::Gainsboro
$subtitle.Location = New-Object System.Drawing.Point(21, 51)
$form.Controls.Add($subtitle)

$searchLabel = New-Object System.Windows.Forms.Label
$searchLabel.Text = "Search:"
$searchLabel.AutoSize = $true
$searchLabel.ForeColor = [System.Drawing.Color]::White
$searchLabel.Font = New-Object System.Drawing.Font("Segoe UI", 10)
$searchLabel.Location = New-Object System.Drawing.Point(20, 86)
$form.Controls.Add($searchLabel)

$searchBox = New-Object System.Windows.Forms.TextBox
$searchBox.Font = New-Object System.Drawing.Font("Segoe UI", 10)
$searchBox.Location = New-Object System.Drawing.Point(88, 82)
$searchBox.Size = New-Object System.Drawing.Size(454, 28)
$searchBox.Anchor = "Top, Left, Right"
$form.Controls.Add($searchBox)

$countLabel = New-Object System.Windows.Forms.Label
$countLabel.AutoSize = $true
$countLabel.ForeColor = [System.Drawing.Color]::LightGray
$countLabel.Font = New-Object System.Drawing.Font("Segoe UI", 9)
$countLabel.Location = New-Object System.Drawing.Point(560, 87)
$countLabel.Anchor = "Top, Right"
$form.Controls.Add($countLabel)

# ---------------------------------------------------------------------------
# Relic table
# ---------------------------------------------------------------------------

$grid = New-Object System.Windows.Forms.DataGridView
$grid.Location = New-Object System.Drawing.Point(20, 122)
$grid.Size = New-Object System.Drawing.Size(1025, 475)
$grid.Anchor = "Top, Bottom, Left, Right"
$grid.ReadOnly = $true
$grid.AllowUserToAddRows = $false
$grid.AllowUserToDeleteRows = $false
$grid.AllowUserToResizeRows = $false
$grid.MultiSelect = $false
$grid.SelectionMode = "FullRowSelect"
$grid.AutoSizeColumnsMode = "Fill"
$grid.RowHeadersVisible = $false
$grid.BackgroundColor = [System.Drawing.Color]::FromArgb(36, 39, 46)
$grid.BorderStyle = "FixedSingle"
$grid.EnableHeadersVisualStyles = $false

$grid.ColumnHeadersDefaultCellStyle.BackColor =
    [System.Drawing.Color]::FromArgb(52, 56, 66)
$grid.ColumnHeadersDefaultCellStyle.ForeColor =
    [System.Drawing.Color]::White
$grid.ColumnHeadersDefaultCellStyle.Font =
    New-Object System.Drawing.Font(
        "Segoe UI",
        9,
        [System.Drawing.FontStyle]::Bold
    )

$grid.DefaultCellStyle.BackColor =
    [System.Drawing.Color]::FromArgb(36, 39, 46)
$grid.DefaultCellStyle.ForeColor =
    [System.Drawing.Color]::WhiteSmoke
$grid.DefaultCellStyle.SelectionBackColor =
    [System.Drawing.Color]::FromArgb(67, 91, 142)
$grid.DefaultCellStyle.SelectionForeColor =
    [System.Drawing.Color]::White
$grid.DefaultCellStyle.Font =
    New-Object System.Drawing.Font("Segoe UI", 9)

$form.Controls.Add($grid)

# ---------------------------------------------------------------------------
# Bottom controls
# ---------------------------------------------------------------------------

$teleportButton = New-Object System.Windows.Forms.Button
$teleportButton.Text = "Teleport"
$teleportButton.Font = New-Object System.Drawing.Font(
    "Segoe UI",
    10,
    [System.Drawing.FontStyle]::Bold
)
$teleportButton.Size = New-Object System.Drawing.Size(145, 39)
$teleportButton.Location = New-Object System.Drawing.Point(20, 612)
$teleportButton.Anchor = "Bottom, Left"
$teleportButton.FlatStyle = "Flat"
$teleportButton.BackColor =
    [System.Drawing.Color]::FromArgb(61, 104, 184)
$teleportButton.ForeColor = [System.Drawing.Color]::White
$form.Controls.Add($teleportButton)

$reloadButton = New-Object System.Windows.Forms.Button
$reloadButton.Text = "Refresh"
$reloadButton.Font = New-Object System.Drawing.Font("Segoe UI", 10)
$reloadButton.Size = New-Object System.Drawing.Size(120, 39)
$reloadButton.Location = New-Object System.Drawing.Point(177, 612)
$reloadButton.Anchor = "Bottom, Left"
$reloadButton.FlatStyle = "Flat"
$reloadButton.BackColor =
    [System.Drawing.Color]::FromArgb(58, 61, 70)
$reloadButton.ForeColor = [System.Drawing.Color]::White
$form.Controls.Add($reloadButton)

$closeButton = New-Object System.Windows.Forms.Button
$closeButton.Text = "Close"
$closeButton.Font = New-Object System.Drawing.Font("Segoe UI", 10)
$closeButton.Size = New-Object System.Drawing.Size(120, 39)
$closeButton.Location = New-Object System.Drawing.Point(925, 612)
$closeButton.Anchor = "Bottom, Right"
$closeButton.FlatStyle = "Flat"
$closeButton.BackColor =
    [System.Drawing.Color]::FromArgb(58, 61, 70)
$closeButton.ForeColor = [System.Drawing.Color]::White
$form.Controls.Add($closeButton)

$statusLabel = New-Object System.Windows.Forms.Label
$statusLabel.Text = "Ready."
$statusLabel.AutoSize = $true
$statusLabel.Font = New-Object System.Drawing.Font("Segoe UI", 9)
$statusLabel.ForeColor = [System.Drawing.Color]::LightGray
$statusLabel.Location = New-Object System.Drawing.Point(315, 622)
$statusLabel.Anchor = "Bottom, Left, Right"
$form.Controls.Add($statusLabel)

# The DataTable contains the full list. The DataView applies live search filters.
$dataTable = $null
$dataView = $null

# Escape special characters used by DataView.RowFilter expressions.
function Escape-RowFilterValue([string]$value) {
    return $value.Replace("'", "''").
        Replace("[", "[[]").
        Replace("%", "[%]").
        Replace("*", "[*]")
}

function Load-RelicData {
    if (-not (Test-Path -LiteralPath $DataFile)) {
        $statusLabel.Text = "The relic data file could not be found."
        return
    }

    try {
        $items = Import-Csv -LiteralPath $DataFile -Delimiter "`t"

        $script:dataTable = New-Object System.Data.DataTable
        [void]$script:dataTable.Columns.Add("Index", [int])
        [void]$script:dataTable.Columns.Add("Relic", [string])
        [void]$script:dataTable.Columns.Add("ActorType", [string])
        [void]$script:dataTable.Columns.Add("X", [double])
        [void]$script:dataTable.Columns.Add("Y", [double])
        [void]$script:dataTable.Columns.Add("Z", [double])

        foreach ($item in $items) {
            $row = $script:dataTable.NewRow()
            $row["Index"] = [int]$item.Index
            $row["Relic"] = [string]$item.Relic
            $row["ActorType"] = [string]$item.ActorType
            $row["X"] = [double]::Parse(
                $item.X,
                [Globalization.CultureInfo]::InvariantCulture
            )
            $row["Y"] = [double]::Parse(
                $item.Y,
                [Globalization.CultureInfo]::InvariantCulture
            )
            $row["Z"] = [double]::Parse(
                $item.Z,
                [Globalization.CultureInfo]::InvariantCulture
            )
            [void]$script:dataTable.Rows.Add($row)
        }

        $script:dataView = New-Object System.Data.DataView($script:dataTable)
        $grid.DataSource = $script:dataView

        # Tune relative column widths for readability.
        if ($grid.Columns["Index"]) {
            $grid.Columns["Index"].FillWeight = 35
        }

        if ($grid.Columns["Relic"]) {
            $grid.Columns["Relic"].HeaderText = "Relic"
            $grid.Columns["Relic"].FillWeight = 100
        }

        if ($grid.Columns["ActorType"]) {
            $grid.Columns["ActorType"].HeaderText = "Actor type"
            $grid.Columns["ActorType"].FillWeight = 180
        }

        foreach ($coordinate in @("X", "Y", "Z")) {
            if ($grid.Columns[$coordinate]) {
                $grid.Columns[$coordinate].FillWeight = 70
                $grid.Columns[$coordinate].DefaultCellStyle.Format = "0.000"
            }
        }

        $searchBox.Text = ""
        $countLabel.Text = "$($script:dataTable.Rows.Count) relics"
        $statusLabel.Text = "List refreshed."
    }
    catch {
        $statusLabel.Text = "Could not read the relic list: $($_.Exception.Message)"
    }
}

function Apply-Filter {
    if ($null -eq $script:dataView) {
        return
    }

    $query = $searchBox.Text.Trim()

    if ([string]::IsNullOrWhiteSpace($query)) {
        $script:dataView.RowFilter = ""
    }
    else {
        $escaped = Escape-RowFilterValue $query
        $script:dataView.RowFilter =
            "Relic LIKE '%$escaped%' OR " +
            "ActorType LIKE '%$escaped%' OR " +
            "Convert([Index], 'System.String') LIKE '%$escaped%'"
    }

    $countLabel.Text =
        "$($script:dataView.Count) / $($script:dataTable.Rows.Count) relics"
}

# Return input focus to the game after the popup sends a teleport command.
function Focus-Palworld {
    Start-Sleep -Milliseconds 120

    $processNames = @(
        "Palworld-Win64-Shipping",
        "Palworld-WinGDK-Shipping",
        "Palworld"
    )

    foreach ($processName in $processNames) {
        $process = Get-Process -Name $processName -ErrorAction SilentlyContinue |
            Where-Object { $_.MainWindowHandle -ne 0 } |
            Select-Object -First 1

        if ($null -ne $process) {
            # 9 = SW_RESTORE
            [void][NativeWindowTools]::ShowWindowAsync(
                $process.MainWindowHandle,
                9
            )
            [void][NativeWindowTools]::SetForegroundWindow(
                $process.MainWindowHandle
            )
            return
        }
    }
}

# Write the selected row index for the Lua script to consume.
function Teleport-SelectedRelic {
    if ($grid.SelectedRows.Count -lt 1) {
        $statusLabel.Text = "Select a relic first."
        return
    }

    $selectedItem = $grid.SelectedRows[0].DataBoundItem

    if ($null -eq $selectedItem) {
        return
    }

    $index = [int]$selectedItem.Row["Index"]
    [System.IO.File]::WriteAllText($CommandFile, [string]$index)

    $statusLabel.Text = "Teleporting to relic #$index..."
    Focus-Palworld
}

# ---------------------------------------------------------------------------
# UI event handlers
# ---------------------------------------------------------------------------

$searchBox.Add_TextChanged({
    Apply-Filter
})

$teleportButton.Add_Click({
    Teleport-SelectedRelic
})

$grid.Add_CellDoubleClick({
    param($sender, $eventArgs)

    if ($eventArgs.RowIndex -ge 0) {
        $grid.Rows[$eventArgs.RowIndex].Selected = $true
        Teleport-SelectedRelic
    }
})

$grid.Add_KeyDown({
    param($sender, $eventArgs)

    if ($eventArgs.KeyCode -eq [System.Windows.Forms.Keys]::Enter) {
        $eventArgs.SuppressKeyPress = $true
        Teleport-SelectedRelic
    }
})

$reloadButton.Add_Click({
    Load-RelicData
})

$closeButton.Add_Click({
    $form.Close()
})

$form.Add_KeyDown({
    param($sender, $eventArgs)

    if ($eventArgs.KeyCode -eq [System.Windows.Forms.Keys]::Escape) {
        $form.Close()
    }
})

# Poll for the SHOW command sent by a second PowerShell process when F8 is
# pressed while the popup is already running.
$uiTimer = New-Object System.Windows.Forms.Timer
$uiTimer.Interval = 200
$uiTimer.Add_Tick({
    if (-not (Test-Path -LiteralPath $UiCommandFile)) {
        return
    }

    try {
        $uiCommand = [System.IO.File]::ReadAllText($UiCommandFile).Trim()

        if ($uiCommand -eq "SHOW") {
            [System.IO.File]::WriteAllText($UiCommandFile, "")
            Load-RelicData

            if (
                $form.WindowState -eq
                [System.Windows.Forms.FormWindowState]::Minimized
            ) {
                $form.WindowState =
                    [System.Windows.Forms.FormWindowState]::Normal
            }

            $form.Show()
            $form.TopMost = $true
            $form.Activate()
            $form.BringToFront()
        }
    }
    catch {
        # Ignore temporary read/write races between the two processes.
    }
})
$uiTimer.Start()

# Clean up runtime files when the popup closes.
$form.Add_FormClosed({
    $uiTimer.Stop()
    Remove-Item -LiteralPath $LockFile -Force -ErrorAction SilentlyContinue
    Remove-Item -LiteralPath $UiCommandFile -Force -ErrorAction SilentlyContinue
})

Load-RelicData
[void]$form.ShowDialog()
